### ISSUE TITLE
The minibatch iterator seems not right.

### ISSUE THREAD

**Issue by tsotfsk** [yeganegi-reza/Torch-GRU4Rec#1]
I use another dataset to train the model. but when it is about end in one epoch， it raise error like

>  F:\GRU\Torch-GRU4Rec-master\Modules\Model.py in resetHidden(self, hidden, finishedMask, validMask)
    134 
    135         if any((~validMask)):
--> 136             hidden = hidden[:, validMask, :]
    137 
    138         return hidden.data;
 IndexError: The shape of the mask [98] at index 0 does not match the shape of the indexed tensor 
 [1, 99, 100] at index 1

**Comment by tsotfsk** [comment]
yield input, target, finishedMask, validMask
finishedMask = (end - start <= 1)
validMask = (iters < nSessions)

I changed these few lines in the Dataset code, and I found that it could solve my problem. The reason for that problem is that the length of the finishMask of your previous code does not match the length of the last target.

**Comment by yeganegi-reza** [comment]
> yield input, target, finishedMask, validMask
> finishedMask = (end - start <= 1)
> validMask = (iters < nSessions)
> 
> I changed these few lines in the Dataset code, and I found that it could solve my problem. The reason for that problem is that the length of the finishMask of your previous code does not match the length of the last target.

Your changes return invalid finishedMask.

This is because your Dataset has sessions that their length is smaller than 2 (sessionLength<=2).
To solve this problem, I've added some codes to delete the unique sessions.
